--- #YAML:1.0
name:               Carp-Clan
version:            5.4
abstract:           Report errors from perspective of caller of a "clan" of modules
author:
    - Steffen Beyer <STBEY@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
